### ISSUE TITLE
The build is borken

### ISSUE THREAD

**Issue by StephenChips** [vuejs/docs#1642]
After cloned the project I install dependencies by `pnpm i`, then I typed in `pnum run dev` and expect the project will start, but it failed and print following message:

```
 C:\Users\Administration\Documents\vue\docs\.vitepress\config.ts:52
    const headers = md.__data?.headers;
                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\23324\Documents\vue\docs\node_modules\.pnpm\vite@2.8.1\node_modules\vite\dist\node\chunks\dep-1412e872.js:71394:20)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadConfigFromBundledFile (C:\Users\23324\Documents\vue\docs\node_modules\.pnpm\vite@2.8.1\node_modules\vite\dist\node\chunks\dep-1412e872.js:71402:17)
    at Object.loadConfigFromFile (C:\Users\23324\Documents\vue\docs\node_modules\.pnpm\vite@2.8.1\node_modules\vite\dist\node\chunks\dep-1412e872.js:71321:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 ELIFECYCLE  Command failed with exit code 1.
```

It seems the typescript is not properly processed. Do I need to install some other dependencies and make some configurations in order to make the project run?

P.S.
Node's version: v12.18.4
pnpm's version: v6.32.3

**Comment by skirtles-code** [comment]
I believe the optional chaining operator was added in Node 14, so that's the minimum version you'll need to run the docs. See <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility>.

**Comment by StephenChips** [comment]
Is there a alternative way that can avoid re-installing node.js? e.g. install a typescript compiler?
